service: dynamodb-crud-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-1
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.leadsTableName}

custom:
  leadsTableName: leads-table-${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function

functions:
  getLead:
    handler: api.getLead
    name: get-lead
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: lead/{id}
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:GetItem"
        Resource: !GetAtt LeadsTable.Arn
  createLead:
    handler: api.createLead
    name: create-lead
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:g
      - http:
          path: lead
          method: lead
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
        Resource: !GetAtt LeadsTable.Arn
  updateLead:
    handler: api.updateLead
    name: update-lead
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: leads/{id}
          method: PUT
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:UpdateItem"
        Resource: !GetAtt LeadsTable.Arn
  deleteLead:
    handler: api.deleteLead
    name: delete-lead
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: lead/{id}
          method: DELETE
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:DeleteItem"
        Resource: !GetAtt LeadsTable.Arn
  getAllLeads:
    handler: api.getAllLeds
    name: get-all-leads
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: leads
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:Scan"
        Resource: !GetAtt LeadsTable.Arn

resources:
  Resources:
    LeadsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.leadsTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
